### ISSUE TITLE
Missing related work

### ISSUE THREAD

**Issue by Ming-er** [qiuk2/AAR#3]
Hi, author, 
I think the core idea of AAR is quite similar with VAR ([Visual autoregressive modeling: Scalable image generation via next-scale prediction](https://arxiv.org/abs/2404.02905)), but I find that there is no discussion about the relationship of the two in the preprint paper. Maybe more discussion will highlight the contribution of AAR.

**Comment by lxa9867** [comment]
Hi, thanks for the suggestion. We have cited the VAR paper in related works and may discuss more in the next version.

Instead of comparing to VAR, we consider the discussion (in the preprint) with vanilla residual quantization (RQ) to be more important. The design of multi-scale residual quantization (MSRQ) is based on the assumption that low-frequency information requires fewer tokens to represent it. This leads to a shorter token length than vanilla RQ.

**Comment by hubertsiuzdak** [comment]
on that note, you might want to reference [SNAC](https://github.com/hubertsiuzdak/snac), in case you overlooked it :)
