### ISSUE TITLE
Would it be possible to use this model to generate audio based on text?

### ISSUE THREAD

**Issue by enhuiz** [qiuk2/AAR#4]
Thanks for sharing the model. The inference script seems to support generating audio from CLAP audio embedding. Does it also support generating form text embedding (like audio generation models)?

I noticed in the paper that the audio clip was divided into n segments (what's n used in the released model?) and then reassembled into a complete audio stream. How is temporal consistency maintained throughout this process?

**Comment by lxa9867** [comment]
Hi,
 
 Thanks for the question. Since the clap model basically aligns the audio and text space, you can modify the code to use text embedding to generate text-conditioned audio.
 
For the tokenizer, we released two versions - 1s and 5s while our code also supports tokenization for longer audios. For example, to tokenize a 10s audio using the 5s SAT, we can divide it into n=2 segments.

Previous methods typically have overlapped windows to enhance consistency. However, in SAT, due to the multi-scale residual quantization, the overlapped window cannot be easily applied in the quantized tokens. We will enhance the reassembly for longer audios in the next version.

**Comment by enhuiz** [comment]
Is the same 1s/5s clip length used for AAR (Transformer)? For example, if I want to generate 2 seconds of audio using an AAR trained with a 1-second tokenizer, would I need to reassemble the output?

**Comment by qiuk2** [comment]
Thanks for your question. Our AAR model currently only support 1s audio generation. If you need to use AAR to generate 2s or more audio, I think you should train another AAR model and need to reassemble the input and output to make sure the temporal consistency.

**Comment by enhuiz** [comment]
I understand now, thanks!
